export {
  NAMING_EVIDENCE_VERSION,
  aggregateNamingEvidence,
  createNamingObservation,
  normalizeNamingObservation,
  serializeNamingEvidence,
  type AcronymObservation,
  type EvidenceValue,
  type KnownEvidence,
  type LexicalToken,
  type NamingAggregates,
  type NamingAnalysis,
  type NamingEvidence,
  type NamingForm,
  type NamingObservation,
  type NamingObservationInput,
  type NamingPosition,
  type NamingSource,
  type NamingSymbolKind,
  type Pluralization,
  type SymbolKindAggregate,
  type TermAggregate,
  type TermKindCount,
  type UnknownEvidence,
  type UnknownReason,
} from "./evidence.js";
export {
  DEFAULT_IGNORED_DIRECTORIES,
  DEFAULT_IGNORED_FILE_PATTERNS,
  NamingDiscoveryError,
  discoverAndSerializeNamingEvidence,
  discoverNamingEvidence,
  type NamingDiscoveryOptions,
} from "./discover.js";
